# .bashrc

# Personal aliases and functions.

# Personal environment variables and startup programs should go in
# ~/.bash_profile.  System wide environment variables and startup
# programs are in /etc/profile.  System wide aliases and functions are
# in /etc/bashrc.


# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

#aliases
alias ls='ls -lhG'
alias glg='git log --date-order --all --graph --format="%C(green)%h%Creset %C(yellow)%an%Creset %C(blue bold)%ar%Creset %C(red bold)%d%Creset%s"'
alias ssh-home="ssh username@home-ip"

